### ISSUE TITLE
Add auto test for the server

### ISSUE THREAD

**Issue by sadym-chromium** [sadym-chromium/WebDriverBiDiServerExperiments#4]
As a developer, I want to:
1. test some commands and verify they work properly;
2. have an easy way to add new tests.

**Comment by foolip** [comment]
I've sent something in https://github.com/sadym-chromium/WebDriverBiDiServerExperiments/pull/5. Not tests, but something.

**Comment by foolip** [comment]
I turned https://github.com/sadym-chromium/WebDriverBiDiServerExperiments/pull/5 into actual tests, but they're not very good, they don't verify anything interesting.
